const {
  ContainerBuilder,
  TextDisplayBuilder,
  SeparatorBuilder,
  MessageFlags,
  PermissionsBitField,
  ChannelType
} = require('discord.js');
const config = require('../../config.json');

module.exports = {
  name: 'createinvite',
  description: 'Creates a SERVER invite link (Owner Only) - Text channels only',
  usage: 'createinvite <guildID> [maxUses] [expireTime]',

  async execute(message, args) {
    if (message.author.id !== config.ownerID) {
      return sendError(message, 'Owner Only Command', '❌ This command can only be used by the bot owner.');
    }

    if (!args[0]) {
      return sendError(message, 'Missing Server ID', '❌ Please provide a server ID. `e.g` createinvite 123456789012345678');
    }

    const guildId = args[0];
    const maxUses = args[1] ? parseInt(args[1]) : 0;
    const expireTime = args[2] ? parseInt(args[2]) : 0;

    try {
      const guild = message.client.guilds.cache.get(guildId);
      if (!guild) {
        return sendError(message, 'Guild Not Found', '❌ Bot is not in that server.');
      }

      const textChannels = guild.channels.cache.filter(channel =>
        channel.type === ChannelType.GuildText &&
        channel.permissionsFor(guild.members.me).has([
          PermissionsBitField.Flags.ViewChannel,
          PermissionsBitField.Flags.CreateInstantInvite
        ])
      );

      if (textChannels.size === 0) {
        const container = new ContainerBuilder()
          .addTextDisplayComponents(new TextDisplayBuilder().setContent(`**No Suitable Text Channels in ${guild.name}**`))
          .addSeparatorComponents(new SeparatorBuilder())
          .addTextDisplayComponents(new TextDisplayBuilder().setContent(
            `❌ No suitable TEXT channels found.\n\n**Requirements:**\n- Must be a text channel (no voice channels)\n- \`View Channel\` permission\n- \`Create Instant Invite\` permission\n\n**Troubleshooting:**\n1. Check bot permissions in text channels\n2. Try a different text channel\n3. Make sure bot role is high enough`
          ));

        return message.channel.send({
          components: [container],
          flags: MessageFlags.IsComponentsV2
        });
      }

      const channel = guild.rulesChannel || guild.publicUpdatesChannel || textChannels.first();

      const invite = await channel.createInvite({
        maxUses: maxUses || undefined,
        maxAge: expireTime || undefined,
        unique: true,
        reason: `Server invite generated by owner ${message.author.tag}`
      });

      await message.author.send(
        `🎟️ **SERVER INVITE LINK** 🎟️\n🔗 https://discord.gg/${invite.code}\n🏠 Server: ${guild.name}\n📊 Max uses: ${maxUses || 'Unlimited'}\n⏳ Expires: ${expireTime ? formatTime(expireTime) : 'Never'}\n\n⚠️ This is a SERVER invite, not VC-specific`
      );

      if (message.deletable) await message.delete();

      const success = new ContainerBuilder()
        .addTextDisplayComponents(new TextDisplayBuilder().setContent('**Invite Sent**'))
        .addSeparatorComponents(new SeparatorBuilder())
        .addTextDisplayComponents(new TextDisplayBuilder().setContent('✅ Server invite link sent to your DMs!'));

      const reply = await message.channel.send({
        components: [success],
        flags: MessageFlags.IsComponentsV2
      });

      setTimeout(() => reply.delete().catch(() => {}), 5000);
    } catch (error) {
      console.error('Server Invite Error:', error);

      return sendError(message, 'Invite Creation Failed', `❌ Failed to create SERVER invite: ${error.message}\n\nMake sure:\n1. Bot has proper permissions\n2. Channel exists and is accessible\n3. Bot role is high enough in hierarchy`);
    }
  }
};

// ✅ Helper: Error Container
function sendError(message, title, description) {
  const container = new ContainerBuilder()
    .addTextDisplayComponents(new TextDisplayBuilder().setContent(`**${title}**`))
    .addSeparatorComponents(new SeparatorBuilder())
    .addTextDisplayComponents(new TextDisplayBuilder().setContent(description));

  return message.channel.send({
    components: [container],
    flags: MessageFlags.IsComponentsV2
  });
}

// ✅ Helper: Format Time
function formatTime(seconds) {
  const days = Math.floor(seconds / 86400);
  const hours = Math.floor((seconds % 86400) / 3600);
  const mins = Math.floor((seconds % 3600) / 60);

  return [
    days > 0 ? `${days} day${days !== 1 ? 's' : ''}` : null,
    hours > 0 ? `${hours} hour${hours !== 1 ? 's' : ''}` : null,
    mins > 0 ? `${mins} minute${mins !== 1 ? 's' : ''}` : null
  ].filter(Boolean).join(' ') || 'less than 1 minute';
}